include: package:dart_test_tools/analysis_options_package.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.freezed.dart"
    - "**/*.g.dart"

linter:
  rules:
    public_member_api_docs: false
