name: firebase_sync

packages:
  - "."

scripts:
  get:
    run: dart pub get

  upgrade:
    run: dart pub upgrade

  build:
    run: dart run build_runner build

  build:watch:
    run: dart run build_runner watch

  test:
    run: dart run dart_test_tools:test

  test:coverage:
    run: dart run dart_test_tools:test -c

  test:coverage:open:
    run: dart run dart_test_tools:test -cho

  test:unit:
    run: dart run dart_test_tools:test -munit

  test:unit:coverage:
    run: dart run dart_test_tools:test -munit -c

  test:unit:coverage:open:
    run: dart run dart_test_tools:test -munit -cho

  test:unit:vm:
    run: dart run dart_test_tools:test -munit -pvm

  test:unit:vm:coverage:
    run: dart run dart_test_tools:test -munit -pvm -c

  test:unit:vm:coverage:open:
    run: dart run dart_test_tools:test -munit -pvm -cho

  test:unit:js:
    run: dart run dart_test_tools:test -munit -pjs

  test:unit:js:coverage:
    run: dart run dart_test_tools:test -munit -pjs -c

  test:unit:js:coverage:open:
    run: dart run dart_test_tools:test -munit -pjs -cho

  test:integration:
    run: dart run dart_test_tools:test -mintegration

  test:integration:vm:
    run: dart run dart_test_tools:test -mintegration -pvm

  test:integration:js:
    run: dart run dart_test_tools:test -mintegration -pjs

  pre-commit:init:
    run: >-
      bash -c "echo -e
      '#!/bin/sh\nexec dart pub global run melos run pre-commit:run'
      > .git/hooks/pre-commit && chmod a+x .git/hooks/pre-commit"
    description: Setup pre commit hooks

  pre-commit:remove:
    run: rm -f .git/hooks/pre-commit
    description: Remove pre commit hooks

  pre-commit:run:
    run: dart run dart_pre_commit -tp -oany --ansi
    description: Run pre commit hooks
