name: firebase_sync
description: A cross platform dart package that provides local synchronization
  with the firebase realtime database.
version: 0.1.0
homepage: https://github.com/Skycoder42/firebase_sync

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  firebase_database_rest: ^1.0.3
  freezed_annotation: ^0.14.3
  hive: ^2.0.4
  json_annotation: ^4.1.0
  meta: ^1.7.0
  path: ^1.8.0
  sodium: ^1.1.2
  synchronized: ^3.0.0
  uuid: ^3.0.5

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.4
  coverage: ^1.0.3
  dart_pre_commit: ^2.3.2
  dart_test_tools: ^1.0.0
  fake_async: ^1.2.0
  freezed: ^0.14.5
  hive_generator: ^1.1.1
  json_serializable: ^5.0.2
  lint: ^1.7.2
  mocktail: ^0.1.4
  test: ^1.18.2
  tuple: ^2.0.0

dart_test_tools:
  publish:
    exclude:
      - lib/src/.gitignore
