name: firebase_sync
description: A cross platform dart package that provides local synchronization
  with the firebase realtime database.
version: 0.1.0
homepage: https://github.com/Skycoder42/firebase_sync

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  firebase_database_rest: ^1.0.3
  freezed_annotation: ^0.14.3
  hive: ^2.0.4
  json_annotation: ^4.1.0
  meta: ^1.7.0
  path: ^1.8.0
  sodium: ^1.1.0
  synchronized: ^3.0.0
  tuple: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  args: ^2.2.0
  build_runner: ^2.1.1
  coverage: ^1.0.3
  dart_pre_commit: ^2.3.2
  freezed: ^0.14.2
  hive_generator: ^1.1.0
  json_serializable: ^4.1.4
  lint: ^1.6.0
  mocktail: ^0.1.4
  test: ^1.17.11
  dart_test_tools:
    git: https://github.com/Skycoder42/dart_test_tools.git

# dependency_overrides:
#   dart_test_tools:
#     path: ../dart_test_tools

dart_test_tools:
  publish:
    exclude:
      - lib/src/.gitignore
