name: firebase_sync
description: A cross platform dart package that provides local synchronization
  with the firebase realtime database.
version: 0.1.0
homepage: https://github.com/Skycoder42/firebase_sync

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  # firebase_database_rest: ^1.0.3
  freezed_annotation: ^1.1.0
  hive: ^2.0.6
  json_annotation: ^4.4.0
  meta: ^1.7.0
  path: ^1.8.0
  sodium: ^1.2.0+2
  synchronized: ^3.0.0
  uuid: ^3.0.6

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.8
  coverage: ^1.1.0
  dart_pre_commit: ^3.0.0
  dart_test_tools: ^3.2.1
  fake_async: ^1.2.0
  freezed: ^1.1.1
  hive_generator: ^1.1.2
  json_serializable: ^6.1.5
  lint: ^1.8.2
  mocktail: ^0.3.0
  test: ^1.20.1
  tuple: ^2.0.0

dart_pre_commit:
  allow_outdated:
    - path
